mysite/mysite/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('signin/', user_views.create_user, name='sign_in'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('', include('one.urls'), name='home'),
]

mysite/one/urls.py
from django.urls import path
from users import views as user_views
from django.contrib.auth import views as auth_views
from . import views

app_name = 'one'
urlpatterns = [
	path('', views.welcome, name='home'),
	path('status/', views.status, name='status'),
	path('status/drop/', views.drop, name='drop'),
	path('signin/', user_views.create_user, name='sign_in'),
	path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
	path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
	path('get_data/', views.get_data, name='data'),
	path('<int:pk>/results/', views.get_results, name='results'),
	path('<int:pk>/details/', views.details, name='detail'),
	path('<int:pk>/details/get_courses/', views.get_courses, name='courses'),
	path('<int:pk>/meetings/<str:course_list>/get_details/', views.get_details , name='meetings'),
	path('<int:pk>/meetings/<str:course_list>/<str:vacant>/<str:full>/register/', views.register_results , name='register_results'),
]

mysite/one/models.py
import datetime

from django.db import models
from django.utils import timezone
from django.forms import ModelForm
from django.contrib.auth.models import User

DAYS = [('Monday', 'MON'),
        ('Tuesday','TUES'),
        ('Wednesday','WED'),
        ('Thursday','THURS'),
        ('Friday','FRI'),
        ('Saturday','SAT'),
        ('Sunday','SUN')]

GRAD_YEAR_CHOICES = ['2020', '2021', '2022', '2023', '2024']

MAJOR_CHOICES = ['Undecided', 'Africana Studies', 'Anthropology', 'Applied Mathematics & Statistics','Archaeology','Behavioral Biology','Biology','Biomedical Engineering','Biophysics','Chemical & Biomolecular Engineering','Chemistry','Civil Engineering','Classics','Cognitive Science','Computer Engineering','Computer Science','Earth & Planetary Sciences','East Asian Studies','Economics','Electrical Engineering','Engineering Mechanics','English','Environmental Engineering','Environmental Science','Environmental Studies','Film & Media Studies','French','General Engineering','German','History','History of Art','History of Science, Medicine & Technology','Interdisciplinary Studies','International Studies','Italian','Materials Science & Engineering','Mathematics','Mechanical Engineering','Medicine, Science & the Humanities','Molecular & Cellular Biology','Natural Sciences','Near Eastern Studies','Neuroscience','Philosophy','Physics','Political Science','Psychology','Public Health Studies','Romance Languages','Sociology','Spanish','Writing Seminars']

class StudentUser(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	hopid = models.CharField(max_length=200)
	jhed = models.CharField(max_length=200)
	major = models.CharField(max_length=100)
	grad_year = models.CharField(max_length=4)
	pre_health = models.BooleanField(default=False)

	def __str__(self):
		return self.jhed

class StudentForm(ModelForm):
	class Meta:
		model = StudentUser
		fields = ['hopid', 'jhed', 'major', 'grad_year', 'pre_health']


class Course(models.Model):
	name = models.CharField(max_length=200)
	prof = models.CharField(max_length=200)
	code = models.CharField(max_length=200, default='0')

	def __str__(self):
		return self.name + ' with Professor ' + self.prof

class CourseForm(ModelForm):
	class Meta:
		model = Course
		fields = ['name', 'code']

class Meeting(models.Model):
	course = models.ForeignKey(Course, on_delete=models.CASCADE)
	start_time = models.CharField(max_length=15)
	end_time = models.CharField(max_length=15)
	day = models.CharField(max_length=10, choices=DAYS)
	location = models.CharField(max_length=200, default='TBD')
	max = models.IntegerField(default=15)
	waitlist = models.ManyToManyField(StudentUser, blank=True, related_name="waitlist")
	students = models.ManyToManyField(StudentUser, blank=True, related_name="students")

	def __str__(self):
		return "(%s): %s, %s - %s" % (self.course.code, self.day, self.start_time, self.end_time)

mysite/one/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.shortcuts import render
from .forms import StudentForm, CourseForm
from .models import Course, Meeting, StudentUser
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required

def welcome(request):
	if request.method == 'POST':
		user = request.user.id
		context = {
			'title': 'Welcome | PILOT Registration'
		}
		return redirect('one:data', context=context)
	else:
		if StudentUser.objects.filter(user=request.user.id).exists():
			return redirect('one:status')
		else:
			return render(request, 'one/welcome.html/')


@login_required
def get_data(request):
	# if this is a POST request we need to process the form data
	if request.method == 'POST':
		# create a form instance and populate it with data from the request:
		form = StudentForm(request.POST)
		user = request.user
		# check whether it's valid:
		if form.is_valid():
			# process the data in form.cleaned_data as required
			student_object, created = StudentUser.objects.get_or_create(user=user)
			student_object.hopid = form.cleaned_data['hopid']
			jhed = form.cleaned_data['jhed']
			student_object.jhed = jhed
			user.email = str(jhed) + '@jhu.edu'
			user.save()
			student_object.grad_year = form.cleaned_data['grad_year']
			student_object.major = form.cleaned_data['major']
			student_object.pre_health = form.cleaned_data['pre_health']
			student_object.save()
			# redirect to a new URL:
			return redirect('one:results', pk=student_object.id)
	# if a GET (or any other method) we'll create a blank form
	else:
		form = StudentForm()
		user = request.user
		context = {
			'title': 'Student Information | PILOT Registration',
			'user': user.username
		}
		return render(request, 'one/student_info.html/', context=context)

@login_required
def get_results(request, pk):
	student = StudentUser.objects.filter(id=pk).first()
	# if this is a POST request we need to process the form data
	if request.method == 'POST':
			return redirect('one:detail', pk=student.id)
	# if a GET (or any other method) we'll create a blank form
	else:
		context = {
			'title': 'Your Information | PILOT Registration',
			'student': student
		}
		return render(request, 'one/results.html/', context=context)

@login_required
def details(request, pk):
	student = StudentUser.objects.filter(id=pk).first()
	courses = Course.objects.all()
	context = {
		'title': 'Courses | PILOT Registration',
		'student': student,
		'course_list': courses
	}
	return render(request, 'one/detail.html/', context=context)

@login_required
def get_courses(request, pk):
	student = StudentUser.objects.filter(id=pk).first()
	course_string = ""
	if request.method == 'POST':
		# create a form instance and populate it with data from the request:
		form = CourseForm(request.POST)
		# check whether it's valid:
		if form.is_valid():
			# process the data in form.cleaned_data as required
			course_list = request.POST.getlist('classes')
			for id in course_list:
				course_string += str(id) + "%"
			# redirect to a new URL:
		return redirect('one:meetings', pk=student.id, course_list=course_string)

@login_required
def get_details(request, pk, course_list):
	student = get_object_or_404(StudentUser, pk=pk)
	course_list = course_list.split('%')
	if request.method == 'POST':
		course_string = ""
		vacant_string = ""
		full_string = ""
		for id in course_list:
			if id != '':
				course_string += str(id) + "%"
				if Meeting.objects.filter(course=get_object_or_404(Course, pk=str(id))).exists():
					data = request.POST[id]
					meeting = get_object_or_404(Meeting, pk=str(data))
					if len(meeting.students.all()) < meeting.max:
						vacant_string += str(data) + "%"
						meeting.students.add(student)
					else:
						full_string += str(data) + "%"
						meeting.waitlist.add(student)
		if full_string == '':
			full_string = "%"
		if vacant_string == '':
			vacant_string = "%"
		return redirect('one:register_results', pk=student.id, course_list=course_string, vacant=vacant_string, full=full_string)
	else:
		object_meetings_dict = {}
		for id in course_list:
			if id != '':
				course = get_object_or_404(Course, pk=id)
				meetings = Meeting.objects.filter(course=course)
				meetings = list(meetings)
				object_meetings_dict[course] = meetings
		context= {
			'title': 'Meeting Times | PILOT Registration',
			'student': student,
			'meetings': object_meetings_dict,
		}
		return render(request, 'one/meetings.html/', context=context)

@login_required
def register_results(request, pk, course_list, vacant, full):
	if request.method == 'POST':
		return redirect('one:status')
	else:
		student = StudentUser.objects.filter(id=pk).first()
		courses = []
		vacant_meetings = []
		full_meetings = []
		course_list = course_list.split('%')
		vacant = vacant.split('%')
		full = full.split('%')
		for id in course_list:
			if id != '':
				course = get_object_or_404(Course, pk=id)
				courses.append(course)

		for id in vacant:
			if id != '':
				meeting = get_object_or_404(Meeting, pk=id)
				vacant_meetings.append(meeting)

		for id in full:
			if id != '':
				meeting = get_object_or_404(Meeting, pk=id)
				full_meetings.append(meeting)
		context = {
			'title': 'Registration Results | PILOT Registration',
			'student' : student,
			'courses': course_list,
			'vacant': vacant_meetings,
			'full': full_meetings
		}
		return render(request, 'one/register_results.html/', context=context)

@login_required
def status(request):
	if request.method == 'POST':
		student = get_object_or_404(StudentUser, user=request.user)
		if not StudentUser.objects.filter(user=request.user.id).exists():
			return render(request, 'one/welcome.html/')
		elif not Meeting.objects.filter(students=student).exists() or Meeting.objects.filter(waitlist=student).exists():
			return redirect('one:results', pk=student.id)
	else:
		user = request.user
		student = get_object_or_404(StudentUser, user=user)
		enrolled = list(Meeting.objects.filter(students=student))
		waitlist = list(Meeting.objects.filter(waitlist=student))

		context = {
			'title': 'Your Status | PILOT Registration',
			'student': student,
			'enrolled': enrolled,
			'waitlist': waitlist
		}
		return render(request, 'one/status.html', context=context)

@login_required
def drop(request):
	if request.method == 'POST':
		student = get_object_or_404(StudentUser, user=request.user)

mysite/one/templates/one/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

	<!-- Bootstrap CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{% static 'one/main.css' %}">

	{% if title %}
		<title>{{ title }}</title>
	{% else %}
		<title>PILOT Registration</title>
	{% endif %}
</head>
<body>
<header class="site-header">
	<nav class="navbar navbar-expand-md navbar-dark bg-white fixed-top">
		<div class="container navigation">
			<a class="navbar-brand mr-4" href="{% url 'one:home' %}">PILOT Registration</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarToggle">
				<div class="navbar-nav mr-auto">
					<a class="nav-item nav-link" href="{% url 'one:home' %}">Home</a>
				</div>
				<!-- Navbar Right Side -->
				<div class="navbar-nav">
					{% if user.is_authenticated %}
					<a class="nav-item nav-link" href="{% url 'one:logout' %}">Logout</a>
					{% else %}
					<a class="nav-item nav-link" href="{% url 'one:login' %}">Login</a>
					<a class="nav-item nav-link" href="{% url 'one:sign_in' %}">Create an Account</a>
					{% endif %}
				</div>
			</div>
		</div>
	</nav>
</header>
<main role="main" class="container">
	<div class="row">
		<div class="col-md-8">
			{% if messages %}
			{% for message in messages %}
			<div class="alert alert-{{ message.tags }}">
				{{ message }}
			</div>
			{% endfor %}
			{% endif %}
			{% block content %}{% endblock %}
			<small>If you have concerns, please reach out to Ariane Kelly at <b>example@jhu.edu</b></small><br>
		</div>

		<div class="col-md-4">
			<div class="content-section">
				<h3>PILOT Updates</h3>
				<p class='text-muted'>You can put any information here you'd like.
				<ul class="list-group">
					<li class="list-group-item list-group-item-light">Semester Changes</li>
					<li class="list-group-item list-group-item-light">Announcements</li>
					<li class="list-group-item list-group-item-light">Rules</li>
					<li class="list-group-item list-group-item-light">etc</li>
				</ul>
				</p>
			</div>
		</div>
	</div>

</main>
<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

mysite/one/templates/one/example.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Title</title>
</head>
<body>

</body>
</html>

mysite/one/templates/one/index.html
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>PILOT Registration</title>
	{% load static %}
</head>
<body>
<h1>Tell us about yourself!</h1>
<form action="get_data/" method="post">
	{% csrf_token %}
	<ul>

		<li><tr><th><label for="id_hopid">Hopid:</label></th><td><input type="text" name="hopid" required id="id_hopid"></td></tr></li>
		<li><tr><th><label for="id_jhed">Jhed:</label></th><td><input type="text" name="jhed" required id="id_jhed"></td></tr></li>
		<li><tr><th><label for="id_major">Major:</label></th><td><select name="major" required id="id_major">
			<option value="Undecided">Undecided</option>
			<option value="Africana Studies">Africana Studies</option>
			<option value="Anthropology">Anthropology</option>
			<option value="Applied Mathematics &amp; Statistics">Applied Mathematics &amp; Statistics</option>
			<option value="Archaeology">Archaeology</option>
			<option value="Behavioral Biology">Behavioral Biology</option>
			<option value="Biology">Biology</option>
			<option value="Biomedical Engineering">Biomedical Engineering</option>
			<option value="Biophysics">Biophysics</option>
			<option value="Chemical &amp; Biomolecular Engineering">Chemical &amp; Biomolecular Engineering</option>
			<option value="Chemistry">Chemistry</option>
			<option value="Civil Engineering">Civil Engineering</option>
			<option value="Classics">Classics</option>
			<option value="Cognitive Science">Cognitive Science</option>
			<option value="Computer Engineering">Computer Engineering</option>
			<option value="Computer Science">Computer Science</option>
			<option value="Earth &amp; Planetary Sciences">Earth &amp; Planetary Sciences</option>
			<option value="East Asian Studies">East Asian Studies</option>
			<option value="Economics">Economics</option>
			<option value="Electrical Engineering">Electrical Engineering</option>
			<option value="Engineering Mechanics">Engineering Mechanics</option>
			<option value="English">English</option>
			<option value="Environmental Engineering">Environmental Engineering</option>
			<option value="Environmental Science">Environmental Science</option>
			<option value="Film &amp; Media Studies">Film &amp; Media Studies</option>
			<option value="French">French</option>
			<option value="General Engineering">General Engineering</option>
			<option value="German">German</option>
			<option value="History">History</option>
			<option value="History of Art">History of Art</option>
			<option value="History of Science, Medicine &amp; Technology">History of Science, Medicine &amp; Technology</option>
			<option value="Interdisciplinary Studies">Interdisciplinary Studies</option>
			<option value="International Studies">International Studies</option>
			<option value="Italian">Italian</option>
			<option value="Materials Science &amp; Engineering">Materials Science &amp; Engineering</option>
			<option value="Mathematics">Mathematics</option>
			<option value="Mechanical Engineering">Mechanical Engineering</option>
			<option value="Medicine, Science &amp; the Humanities">Medicine, Science &amp; the Humanities</option>
			<option value="Molecular &amp; Cellular Biology">Molecular &amp; Cellular Biology</option>
			<option value="Natural Sciences">Natural Sciences</option>
			<option value="Near Eastern Studies">Near Eastern Studies</option>
			<option value="Neuroscience">Neuroscience</option>
			<option value="Philosophy">Philosophy</option>
			<option value="Physics">Physics</option>
			<option value="Political Science">Political Science</option>
			<option value="Psychology">Psychology</option>
			<option value="Public Health Studies">Public Health Studies</option>
			<option value="Romance Languages">Romance Languages</option>
			<option value="Sociology">Sociology</option>
			<option value="Spanish">Spanish</option>
			<option value="Writing Seminars">Writing Seminars</option>
		</select></td></tr></li>
		<li><tr><th><label for="id_grad_year">Grad year:</label></th><td><select name="grad_year" required id="id_grad_year">
			<option value="2020">2020</option>
			<option value="2021">2021</option>
			<option value="2022">2022</option>
			<option value="2023">2023</option>
			<option value="2024">2024</option>
		</select></td></tr></li>
		<li><tr><th><label for="id_pre_health">Pre health:</label></th><td><select name="pre_health" required id="id_pre_health">
			<option value="True">Yes</option>
			<option value="False">No</option>
		</select></td></tr></li><br>
		<input type="submit" value="Submit">
	</ul>
</form>

</body>
</html>

mysite/one/templates/one/meetings.html
{% extends "one/base.html" %}
{% block content %}
<div class="content-section">
<h3>Hello, {{ student.jhed }}! </h3>
	<p class="text-muted">These are the PILOT meeting times associated with the courses you chose. Please select only one preferred meeting time per course!</p>
	<form method="post" class="meetings_form">
		{% csrf_token %}
		{% for course, meeting in meetings.items %}
			<h5>{{ course }}</h5>
			<ul>
			{% for time in meeting %}
					<li><input type="radio" name="{{course.id}}" value="{{time.id}}">
						{{ time }}
						{% if time.enrollment >= time.max %}
						- *WAITLIST ONLY*
						{% endif %}
					</li>
			{% endfor %}
			</ul>
		<br>
		{% endfor %}
		<input type="submit" value="Submit">
	</form>
</div>
{% endblock content%}

mysite/one/templates/one/register_results.html
{% extends "one/base.html" %}
{% block content %}
<div class="content-section">
	<h3>Hello, {{student.jhed }}!</h3>
	<p class="text-muted">Here are the PILOT sections you have selected, click 'Confirm' to solidify your registration results! </p>
	<div class="article-metadata">
	<h5>You were <b>successfully</b> enrolled in the following PILOT sections: </h5>
	</div><br>
		{% if vacant|length > 0 %}
			{% for time in vacant %}
				<h6 class="stat-course"><b>{{ time.course }}</b></h6>
				<ul>
					<li><b>Day: </b>{{ time.day }}</li>
					<li><b>Time: </b>{{time.start_time}} - {{time.end_time}}</li>
					<li><b>Location: </b>{{time.location}}</li>
				</ul>
			{% endfor %}
		{% else %}
			<h6 class="stat-course">You are not enrolled in any sections..</h6>
		{% endif %}
		<br>
	<div class="article-metadata">
	<h5>You were <b>waitlisted</b> for the following PILOT sections: </h5>
	</div><br>
	{% if full|length > 0 %}
		{% for time in full %}
			<h6 class="stat-course"><b>{{ time.course }}</b></h6>

			<ul>
				<li><b>Day: </b>{{ time.day }}</li>
				<li><b>Time: </b>{{time.start_time}} - {{time.end_time}}</li>
				<li><b>Location: </b>{{time.location}}</li>
			</ul>
		{% endfor %}
	{% else %}
			<h6 class="stat-course">You are not waitlisted for any sections.</h6>
	{% endif %}
		<br>
		<form method="post">
			{% csrf_token %}
			<input type="submit" value="Confirm">
		</form><br>
		<h7>You will receive an email confirmation to <b>{{student.jhed}}@jhu.edu</b> with your registration results.</h7><br>
	<small>If you have concerns, please reach out to Ariane Kelly at <b>example@jhu.edu</b></small><br>
</div>
{% endblock content %}

mysite/one/templates/one/results.html
{% extends "one/base.html" %}
{% block content %}
<div class="content-section">
	<h3>Hello, {{ student.jhed }}</h3>
	<p class="text-muted">Here is the information you have provided. Please verify that all your data is correct! It is very important that we receive accurate information throughout the registration process.</p>
	<ul>
		<li><b>Username:</b> {{user.username}}</li>
		<li><b>HOPID:</b> {{student.hopid}}</li>
		<li><b>JHED:</b> {{student.jhed}}</li>
		<li><b>Major:</b> {{student.major}}</li>
		<li><b>Graduation Year:</b> {{student.grad_year}}</li>
		<li><b>Pre-Health:</b> {{student.pre_health}}</li>
	</ul><br><br>
		<button>
		<a style="text-decoration: none; color: darkgreen;" href="{% url 'one:detail' student.id %}">Confirm</a>
	</button>
		<button>
			<a style="text-decoration: none; color: darkred;" href="{% url 'one:data' %}">Enter Again</a>
		</button>

</div>
{% endblock content %}

mysite/one/templates/one/student_info.html
{% extends "one/base.html" %}
{% block content %}
<div class="content-section">
	<h3>Hey, {{ user }}! Tell us about yourself!</h3>
	<p class="text-muted">Please enter your JHU information below! In order for your registration request to be processed properly, your information must be correct! </p>
	<form method="post">
		{% csrf_token %}
		<ul>
			<li><tr><th><label for="id_hopid">Hopid:</label></th><td><input type="text" name="hopid" required id="id_hopid"></td></tr></li>
			<li><tr><th><label for="id_jhed">Jhed:</label></th><td><input type="text" name="jhed" required id="id_jhed"></td></tr></li>
			<li><tr><th><label for="id_major">Major:</label></th><td><select name="major" required id="id_major">
				<option value="Undecided">Undecided</option>
				<option value="Africana Studies">Africana Studies</option>
				<option value="Anthropology">Anthropology</option>
				<option value="Applied Mathematics &amp; Statistics">Applied Mathematics &amp; Statistics</option>
				<option value="Archaeology">Archaeology</option>
				<option value="Behavioral Biology">Behavioral Biology</option>
				<option value="Biology">Biology</option>
				<option value="Biomedical Engineering">Biomedical Engineering</option>
				<option value="Biophysics">Biophysics</option>
				<option value="Chemical &amp; Biomolecular Engineering">Chemical &amp; Biomolecular Engineering</option>
				<option value="Chemistry">Chemistry</option>
				<option value="Civil Engineering">Civil Engineering</option>
				<option value="Classics">Classics</option>
				<option value="Cognitive Science">Cognitive Science</option>
				<option value="Computer Engineering">Computer Engineering</option>
				<option value="Computer Science">Computer Science</option>
				<option value="Earth &amp; Planetary Sciences">Earth &amp; Planetary Sciences</option>
				<option value="East Asian Studies">East Asian Studies</option>
				<option value="Economics">Economics</option>
				<option value="Electrical Engineering">Electrical Engineering</option>
				<option value="Engineering Mechanics">Engineering Mechanics</option>
				<option value="English">English</option>
				<option value="Environmental Engineering">Environmental Engineering</option>
				<option value="Environmental Science">Environmental Science</option>
				<option value="Film &amp; Media Studies">Film &amp; Media Studies</option>
				<option value="French">French</option>
				<option value="General Engineering">General Engineering</option>
				<option value="German">German</option>
				<option value="History">History</option>
				<option value="History of Art">History of Art</option>
				<option value="History of Science, Medicine &amp; Technology">History of Science, Medicine &amp; Technology</option>
				<option value="Interdisciplinary Studies">Interdisciplinary Studies</option>
				<option value="International Studies">International Studies</option>
				<option value="Italian">Italian</option>
				<option value="Materials Science &amp; Engineering">Materials Science &amp; Engineering</option>
				<option value="Mathematics">Mathematics</option>
				<option value="Mechanical Engineering">Mechanical Engineering</option>
				<option value="Medicine, Science &amp; the Humanities">Medicine, Science &amp; the Humanities</option>
				<option value="Molecular &amp; Cellular Biology">Molecular &amp; Cellular Biology</option>
				<option value="Natural Sciences">Natural Sciences</option>
				<option value="Near Eastern Studies">Near Eastern Studies</option>
				<option value="Neuroscience">Neuroscience</option>
				<option value="Philosophy">Philosophy</option>
				<option value="Physics">Physics</option>
				<option value="Political Science">Political Science</option>
				<option value="Psychology">Psychology</option>
				<option value="Public Health Studies">Public Health Studies</option>
				<option value="Romance Languages">Romance Languages</option>
				<option value="Sociology">Sociology</option>
				<option value="Spanish">Spanish</option>
				<option value="Writing Seminars">Writing Seminars</option>
			</select></td></tr></li>
			<li><tr><th><label for="id_grad_year">Grad year:</label></th><td><select name="grad_year" required id="id_grad_year">
				<option value="2020">2020</option>
				<option value="2021">2021</option>
				<option value="2022">2022</option>
				<option value="2023">2023</option>
				<option value="2024">2024</option>
			</select></td></tr></li>
			<li><tr><th><label for="id_pre_health">Pre health:</label></th><td><select name="pre_health" required id="id_pre_health">
				<option value="True">Yes</option>
				<option value="False">No</option>
			</select></td></tr></li><br>
			<input type="submit" value="Submit">
		</ul>
	</form>
</div>
{% endblock content %}

mysite/one/templates/one/welcome.html
{% extends "one/base.html" %}
{% block content %}
<div class="content-section">
	<form method="post">
		{% csrf_token %}
		<fieldset>
				<h3>
				Welcome to PILOT Registration!
				</h3>
			<p class="text-muted">Create an account in order to register for sections, keep up with the status of your enrollments, and more!</p>
		</fieldset>
		{% if user.is_authenticated %}
		<div>
			<button type="submit">Begin Registration!</button>
		</div>
		{% else %}
		<div>
			<button type="submit" disabled>You are not logged in!</button>
		</div>
		{% endif %}
	</form>
</div>
{% endblock content %}